# Generated by Django 4.2.5 on 2023-09-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_authorbook_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorbook',
            name='gender',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
