# Generated by Django 4.2.5 on 2023-09-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_authorbook_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author_name',
        ),
        migrations.AddField(
            model_name='product',
            name='author_book',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='product.authorbook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authorbook',
            name='gender',
            field=models.BooleanField(blank=True, default=True, help_text="Is author's gender male"),
        ),
    ]
