# Generated by Django 4.2.5 on 2023-09-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='name',
        ),
    ]
